### ISSUE TITLE
Update 1.0.7 is not suitable for windows

### ISSUE THREAD

**Issue by rugved88** [ZFTurbo/segmentation_models_3D#31]
The requirement is 'tensorflow>=2.13.0, <=2.15.0'.
However, for windows the GPU is not available for tensorflow>=2.10.0

**Comment by ZFTurbo** [comment]
It's available. As I remember It's included in ordinary tensor flow without _gpu suffix. I will check.

**Comment by ZFTurbo** [comment]
Yes, you are right...

![изображение](https://github.com/ZFTurbo/segmentation_models_3D/assets/4013811/f2904709-9d8e-4f4b-855b-dad12ebc426b)

The solution is to install previous version of package 1.0.5 will do as I remember.

**Comment by rugved88** [comment]
Yeah! thanks for the updates. I installed TensorFlow==2.8.0 and segmentation-models-3D==1.0.6 and it worked for me with GPU on windows.
